security:
#password cf client will use when interacting with broker
  user.password: ${USER_PASSWORD:}

h2o:
  provisioner:
    url: localhost
    memory: 512m
    nodes: 1
    timeout: 120

yarn.config: ${YARN_CONFIG:{"HADOOP_CONFIG_KEY":{}}}

nats:
  url: nats://localhost:4222
  serviceCreationTopic: 

cf:
  #name of service in cloud foundry catalog
  servicename: 
  #id of service in cloud foundry catalog
  serviceid: 
  baseid: e74b9df2-717d-429e-9b1a-0ae6933b9381

metadata:
  imageUrl: ${IMAGE_URL:}

logging:
  level:
    water: DEBUG
    org.trustedanalytics: INFO
