security:
#password cf client will use when interacting with broker
  user.password: ${USER_PASSWORD:password}

h2o:
  provisioner:
    url: http://localhost:9090
    memory: 512m
    nodes: 1
    timeout: 120

yarn.config: ${YARN_CONFIG:{"HADOOP_CONFIG_KEY":{}}}

catalog:
  url: ${CATALOG_URL:http://localhost:9090}
  user: ${CATALOG_USER:admin}
  password: ${CATALOG_PASSWORD:password}
  hostname_key: hostname
  login_key: login
  password_key: password

nats:
  url: nats://localhost:4222
  serviceCreationTopic:

cf:
  #name of service in cloud foundry catalog
  servicename: ${SERVICE_NAME:h2o}
  #id of service in cloud foundry catalog
  serviceid: ${SERVICE_ID:h2o}
  baseid: ${BASE_GUID:h2o}

metadata:
  imageUrl: ${IMAGE_URL:}

logging:
  level:
    water: DEBUG
    org.trustedanalytics: INFO
    org.cloudfoundry: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
    